__author__ = 'rogersjeffrey'

"""
  This program reads in a counts file that is generated by running the following command

       python count cfg_freqs.py parse_train.dat > cfg.counts

  The second input is the training file  that has the parse trees of the training data

  The third input is the name of the modified training data file that  replaces the words whose counts are lesser than 5
  with the symbol _RARE_

  python 4.py <cfg.counts> <parse_train.dat> <parse_modified_train_dat>

"""
import TreeUtils
import RuleUtils
from sys import  argv
import json
(script_name,count_file_path,train_data_path,modified_train_file)=argv
instance=TreeUtils.TreeUtils()
rule_utils=RuleUtils.RuleUtils(count_file_path,script_name)
rule_utils.populate_count_dictionaries()
rule_utils.modify_training_data_with_rare(train_data_path,modified_train_file)

